version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.10
  build:
    commands:
      - sam build --template template.yml --manifest layers\requirements.txt
      - sam package --template-file .aws-sam/build/template.yaml --s3-bucket abhipriya-test-bucket --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml
